### ISSUE TITLE
Unexpected NaN in tetr or arrow

### ISSUE THREAD

**Issue by hypcos** [Naruyoko/OmegaNum.js#18] opened 2019-06-08 15:10 UTC
```
OmegaNum(3).tetr(OmegaNum(3).pow(1000).div(OmegaNum(3).pow(990))).toString()
"NaN"
OmegaNum(3).arrow(5)(OmegaNum(3).pow(1000).div(OmegaNum(3).pow(990))).toString()
"NaN"
```

**Comment by Reinhardt-C** [comment] 2019-09-01 01:55
This is because of rogue floating point decimals, meaning that OmegaNum(3).pow(1000).div(OmegaNum(3).pow(990)) doesn't result in 59049 but instead 59049.000000000226 which doesn't pass the isint test for tetr or arrow. I'll try and fix it :)

**Comment by Reinhardt-C** [comment] 2019-09-01 02:08
This is annoying, I don't want to compromise the libraries actual precision to fix small floating point errors, but in not doing so its creating more serious errors. I'll propose a change, but it's not up to me as to whether Naruyoko will accept it.

**Comment by Reinhardt-C** [comment] 2019-09-01 02:43
When this is pushed, it fixed the error and this can be closed :)

**Comment by Reinhardt-C** [comment] 2019-09-04 19:22
The issue is fixed now :)

**Comment by Reinhardt-C** [comment] 2019-09-06 02:15
@Naruyoko  You can close this now, I fixed it in my last update :)

**Closed** 2019-10-12 23:03 UTC
Labels: bug
